### ISSUE TITLE
Improve UX when standalone go-ipfs is already running

### ISSUE THREAD

**Issue by koo5** [ipfs/ipfs-webui#1870]
i installed the IPFS companion extension (in firefox) and tried to "import" a file into my node. This action led me to this url: http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/
I get a sidebar there and some loading-like logo thing for a while, and then the page turns blank, so i check out the console. full log:

<details>
  <summary>Click to expand</summary>

```
 asm.js type error: Asm.js optimizer disabled because no suitable wasm compiler is available 5.46be50cc.chunk.js
09:55:18.752 IPFS Web UI - v2.13.0 - https://github.com/ipfs-shipyard/ipfs-webui/commit/44a46ba main.ab164c00.chunk.js:1:143439
09:55:18.801 react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour. 5.46be50cc.chunk.js:2:74889
09:55:18.847
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/app.json
[HTTP/1.1 404 Not Found 1ms]

09:55:18.849
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/welcome.json
[HTTP/1.1 404 Not Found 1ms]

09:55:18.854
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/status.json
[HTTP/1.1 404 Not Found 1ms]

09:55:18.855
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/files.json
[HTTP/1.1 404 Not Found 2ms]

09:55:18.856
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/explore.json
[HTTP/1.1 404 Not Found 1ms]

09:55:18.857
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/settings.json
[HTTP/1.1 404 Not Found 1ms]

09:55:18.857
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/peers.json
[HTTP/1.1 404 Not Found 2ms]

09:55:18.858
XHRGEThttp://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/locales/en-US/notify.json
[HTTP/1.1 404 Not Found 2ms]

09:55:19.280
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:55:19.367
XHRPOSThttp://127.0.0.1:5001/api/v0/config/show
[HTTP/1.1 200 OK 7895ms]

09:55:19.368
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 7893ms]

09:55:19.398
XHRPOSThttp://127.0.0.1:5001/api/v0/repo/stat
[HTTP/1.1 200 OK 7865ms]

09:55:27.280
loadable-components: failed to asynchronously load component 
Object { fileName: undefined, chunkName: undefined, error: "Loading CSS chunk 9 failed.\n(./static/css/9.d3b2790b.chunk.css)" }
5.46be50cc.chunk.js:2:45058
09:55:27.288
Error: Loading CSS chunk 9 failed.
(./static/css/9.d3b2790b.chunk.css)
    onerror http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/:1
    EventHandlerNonNull*f.e/o[e]< http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/:1
    e http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/:1
    Xe http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/main.ab164c00.chunk.js:1
    resolveAsync http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/5.46be50cc.chunk.js:2
    loadAsync http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/5.46be50cc.chunk.js:2
5.46be50cc.chunk.js:2:832255
09:55:27.297 Loading failed for the <script> with source “http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/13.da464701.chunk.js”. bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva:1:1
09:55:27.298 Loading failed for the <script> with source “http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/9.5a744be9.chunk.js”. bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva:1:1
09:55:27.298 Loading failed for the <script> with source “http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/0.ab934e5a.chunk.js”. bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva:1:1
09:55:27.303
Uncaught (in promise) Error: Loading CSS chunk 9 failed.
(./static/css/9.d3b2790b.chunk.css)
    onerror http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/:1
    EventHandlerNonNull*f.e/o[e]< http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/:1
    e http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/files/ipfs-companion-imports/2021-10-26_095355/:1
    Xe http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/main.ab164c00.chunk.js:1
    resolveAsync http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/5.46be50cc.chunk.js:2
    loadAsync http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/5.46be50cc.chunk.js:2
bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva:1:1505
09:55:27.305 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/main.ab164c00.chunk.js
Source Map URL: main.ab164c00.chunk.js.map

09:55:27.311 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/5.46be50cc.chunk.js
Source Map URL: 5.46be50cc.chunk.js.map
2
09:55:27.314 Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/static/js/main.ab164c00.chunk.js
Source Map URL: main.ab164c00.chunk.js.map

09:55:27.344
XHRGEThttp://bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss.ipfs.localhost:8080/
09:55:27.346
XHRPOSThttp://127.0.0.1:5001/api/v0/id
[HTTP/1.1 200 OK 0ms]

09:55:27.353 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss.ipfs.localhost:8080/. (Reason: CORS request did not succeed).

09:55:27.354
Unable to use the subdomain gateway at http://bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss.ipfs.localhost:8080/. Regular gateway will be used as a fallback TypeError: NetworkError when attempting to fetch resource. main.ab164c00.chunk.js:1:80288
09:55:27.375
XHRGEThttp://0.0.0.0:8080/ipfs/bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss
09:55:27.378
Unable to use the gateway at http://0.0.0.0:8080. The public gateway will be used as a fallback TypeError: NetworkError when attempting to fetch resource. main.ab164c00.chunk.js:1:79673
09:55:27.378 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://0.0.0.0:8080/ipfs/bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss. (Reason: CORS request did not succeed).

09:55:27.396
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:55:32.461
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:55:39.391
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:55:40.070
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:55:47.077
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:55:54.083
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:55:55.092
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:56:02.088
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:09.096
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:10.095
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:56:17.102
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:25.107
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:26.108
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:56:31.202
XHRPOSThttp://127.0.0.1:5001/api/v0/config/show
[HTTP/1.1 200 OK 1ms]

09:56:31.368
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:31.431
XHRPOSThttp://127.0.0.1:5001/api/v0/repo/stat
[HTTP/1.1 200 OK 1ms]

09:56:38.437
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:39.448
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:56:46.449
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:53.454
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:56:54.459
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:57:01.461
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:08.465
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:09.465
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:57:16.471
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:22.528
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:22.579
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:57:27.683
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:34.129
XHRPOSThttp://127.0.0.1:5001/api/v0/config/show
[HTTP/1.1 200 OK 1ms]

09:57:34.131
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 1ms]

09:57:34.176
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:57:34.361
XHRPOSThttp://127.0.0.1:5001/api/v0/repo/stat
[HTTP/1.1 200 OK 1ms]

09:57:41.238
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:48.234
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:57:49.233
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:57:56.241
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:03.255
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:04.255
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:58:11.269
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:18.276
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:19.277
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:58:26.305
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:33.311
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:34.318
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:58:34.326
XHRPOSThttp://127.0.0.1:5001/api/v0/config/show
[HTTP/1.1 200 OK 1ms]

09:58:35.325
XHRPOSThttp://127.0.0.1:5001/api/v0/repo/stat
[HTTP/1.1 200 OK 1ms]

09:58:42.325
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:48.383
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:48.421
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:58:53.666
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 1ms]

09:58:58.790
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:58:58.832
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:59:04.002
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 14ms]

09:59:09.139
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:59:09.189
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:59:14.339
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:59:19.437
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:59:19.440
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:59:24.555
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:59:29.673
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]

09:59:29.724
XHRPOSThttp://127.0.0.1:5001/api/v0/swarm/peers?verbose=true&timeout=10000ms
[HTTP/1.1 200 OK 0ms]

09:59:34.829
XHRPOSThttp://127.0.0.1:5001/api/v0/config/show
[HTTP/1.1 200 OK 1ms]

09:59:34.843
XHRPOSThttp://127.0.0.1:5001/api/v0/stats/bw
[HTTP/1.1 200 OK 0ms]
```

```
asm.js type error: Asm.js optimizer disabled because no suitable wasm compiler is available 5.46be50cc.chunk.js
```
 - ¯\_(ツ)_/¯

```
09:55:18.752 IPFS Web UI - v2.13.0 - https://github.com/ipfs-shipyard/ipfs-webui/commit/44a46ba main.ab164c00.chunk.js:1:143439
``` 
- the commit isn't there. It's a 404.

```
09:55:18.801 react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour. 5.46be50cc.chunk.js:2:74889
```
 - i'm not, i prefer svelte, personally, but i don't think that matters here?

</details>

**Comment by lidel** [comment]
@koo5 what go-ipfs version, browser and operating system are you running?
Is the issue present when you use different browser or open webui in a incognito window?

**Comment by koo5** [comment]
hi. my apologies, the crux of the issue was that i already had an ipfs daemon listening on the same ports that the one spawned by ipfs-desktop was trying to bind to. There could probably be a little smarter error reporting all around, but for now i'm good. :)

**Comment by lidel** [comment]
@koo5 what would be your idea of handling that scenario? I think we have code that checks if 8080 is used by non-IPFS things, but we may be missing check for duplicate node because some folks preferred to run go-ipfs manually.

Do you think it would be less confusing if ipfs-desktop detected that a different node is already present and refuse to start at all?

**Comment by koo5** [comment]
I tried again with "my own" node and everything works, but what seems to (obviously) break things is when the node is running with a custom swarm key. I guess maybe there might have been some assets already cached on my node and then i changed it to a custom swarm, so, that made things really confusing.

now when i'm trying with a custom swarm key again, the file import function eventually takes me to http://webui.ipfs.io.ipns.localhost:8080/ which ends up a blank page.

so i guess ipfs-companion should have a check that alerts users if it's not able to load all it's assets?

**Comment by lidel** [comment]
Using [experimental configuration with swarm key](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks)  means your node can only exchange data with peers that share the same swarm key. 

ipfs-webui is fetched from ... IPFS so you blocked yourself from fetching its assets.
We do not support private swarms in companion nor in webui – this is experimental feature, YMMV.
